============================= test session starts ==============================
platform linux -- Python 3.11.13, pytest-8.4.1, pluggy-1.6.0
rootdir: /workspaces/batch_file_processor
plugins: cov-6.2.1
collected 109 items

tests/test_adjust_column_width.py .                                      [  0%]
tests/test_backup_increment.py .                                         [  1%]
tests/test_batch_log_sender.py .                                         [  2%]
tests/test_convert_to_csv.py .....                                       [  7%]
tests/test_convert_to_estore_einvoice.py .                               [  8%]
tests/test_convert_to_estore_einvoice_generic.py ....                    [ 11%]
tests/test_convert_to_fintech.py .                                       [ 12%]
tests/test_convert_to_jolley_custom.py .                                 [ 13%]
tests/test_convert_to_scannerware.py .....                               [ 18%]
tests/test_convert_to_scansheet_type_a.py .                              [ 19%]
tests/test_convert_to_simplified_csv.py .......                          [ 25%]
tests/test_convert_to_stewarts_custom.py ..                              [ 27%]
tests/test_convert_to_yellowdog_csv.py ..                                [ 29%]
tests/test_copy_backend.py .                                             [ 30%]
tests/test_create_database.py F                                          [ 31%]
tests/test_database_import.py .                                          [ 32%]
tests/test_dialog.py E                                                   [ 33%]
tests/test_dispatch.py ....                                              [ 36%]
tests/test_edi_tweaks.py .........                                       [ 44%]
tests/test_email_backend.py .                                            [ 45%]
tests/test_folders_database_migrator.py .                                [ 46%]
tests/test_ftp_backend.py .                                              [ 47%]
tests/test_interface.py .                                                [ 48%]
tests/test_interface_databaseobj.py ......F.                             [ 55%]
tests/test_mover.py FF.FF                                                [ 60%]
tests/test_mtc_edi_validator.py ...F                                     [ 64%]
tests/test_print_run_log.py .                                            [ 65%]
tests/test_query_runner.py .                                             [ 66%]
tests/test_rclick_menu.py .                                              [ 66%]
tests/test_record_error.py .                                             [ 67%]
tests/test_resend_interface.py .                                         [ 68%]
tests/test_utils.py ..............F.FFFFFF.........FF.
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/_pytest/main.py", line 289, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/_pytest/main.py", line 343, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/_pytest/logging.py", line 801, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/_pytest/terminal.py", line 688, in pytest_runtestloop
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "/usr/local/py-utils/venvs/pytest/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     teardown.send(result)
INTERNALERROR>   File "/home/vscode/.local/lib/python3.11/site-packages/pytest_cov/plugin.py", line 346, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/home/vscode/.local/lib/python3.11/site-packages/pytest_cov/engine.py", line 57, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/vscode/.local/lib/python3.11/site-packages/pytest_cov/engine.py", line 320, in finish
INTERNALERROR>     self.cov.combine()
INTERNALERROR>   File "/home/vscode/.local/lib/python3.11/site-packages/coverage/control.py", line 867, in combine
INTERNALERROR>     combine_parallel_data(
INTERNALERROR>   File "/home/vscode/.local/lib/python3.11/site-packages/coverage/data.py", line 165, in combine_parallel_data
INTERNALERROR>     hasher.update(fobj.read())
INTERNALERROR> TypeError: Strings must be encoded before hashing

============= 16 failed, 92 passed, 25 warnings, 1 error in 40.63s =============
